Ecommerce.UI/Controllers/HomeController.cs
using Ecommerce.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService _productService;


        public HomeController(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IActionResult> Index()
        {
            var product = await _productService.GetAll();
            return View(product.Data);
        }
    }
}

Ecommerce.UI/ViewComponents/CategoryListViewComponent.cs
using Ecommerce.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.UI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var category =await  _categoryService.GetAll();
            return View(category.Data);
        }

    }
}

Ecommerce.UI/Views/Home/Index.cshtml
@model Ecommerce.Core.DTos.ProductDTos.ProductListDto


    <div class="row">
        <div class="col-md-3">
           @await Component.InvokeAsync("CategoryList")
        </div>
        <div class="col-md-9">

            <partial name="_slider" />

            <div class="row">
                @foreach (var product in Model.Product)
                {
                    <div class="col-md-4">
                        <div class="card mb-3">
                            <img src="@product.ImageUrl" height="280" alt="@product.Name" />
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">@product.Name</a>
                                </h4>
                                <small class="text-muted">
                                    <i class="fas fa-lira-sign"></i> @product.Price TL
                                </small>
                            </div>
                            <div class="card-footer text-center">
                                <a href="#" class="btn btn-outline-primary btn-lg">Sepete Ekle</a>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>