Ecommerce.UI/Controllers/CartController.cs
using Ecommerce.Business.Interfaces;
using Ecommerce.Core.DTos.CartDTos;
using Ecommerce.Entities.Concrete;
using Ecommerce.UI.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.UI.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly UserManager<User> _userManager;

        public CartController(ICartService cartService, UserManager<User> userManager)
        {
            _cartService = cartService;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var cart = await _cartService.GetByUserOptional(int.Parse(_userManager.GetUserId(User)));
            var cartInstance = cart.Data;
            return View(new CartModel 
            {
                 CartId=cartInstance.Id,
                 CartItems=cartInstance.CartItems.Select(c=>new CartItemModel()
                 {
                     CartItemId=c.Id,
                     ProductId=c.ProductId,
                     Name=c.Product.Name,
                     Price=c.Product.Price.ToString(),
                     ImageUrl=c.Product.ImageUrl

                 }).ToList()
            }) ;
        }
    }
}

Ecommerce.UI/Controllers/UserController.cs
using AutoMapper;
using Ecommerce.Business.Interfaces;
using Ecommerce.Core.DTos.UserDTos;
using Ecommerce.Core.Utilities;
using Ecommerce.Entities.Concrete;
using Ecommerce.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Core.Utilities.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Ecommerce.UI.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly ICartService _cartService;

        public UserController(UserManager<User> userManager, SignInManager<User> signInManager, ICartService cartService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _cartService = cartService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GirisYap(AppUserSignInModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    var identityResult = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, false);
                    if (identityResult.Succeeded)
                    {
                        var rol = await _userManager.GetRolesAsync(user);

                        if (rol.Contains("Admin"))
                        {
                            return RedirectToAction("Index", "Home", new { area = "Admin" });
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home", new { area = "Member" });

                        }
                    }
                }
                ModelState.AddModelError("", "Kullanıcı adın veya şifren hatalı dostum");
            }
            return View("Index", model);
        }
        public IActionResult KayıtOl()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> KayıtOl(AppUserViewModel model)
        {
            if (ModelState.IsValid)
            {

                User user = new User()
                {
                    UserName = model.UserName,
                    Email = model.Email,
                    FirstName = model.Name,
                    LastName = model.Surname,


                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await _cartService.CartAsync(user.Id.ToString());
                    var addRoleResult = await _userManager.AddToRoleAsync(user, "Member");
                    if (addRoleResult.Succeeded)
                    {
                        return RedirectToAction("GirisYap");
                    }
                    foreach (var item in addRoleResult.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(model);

        }
        public async Task<IActionResult> CıkısYap()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Ecommerce.UI/Views/Shared/_Layout.cshtml
@*@inject SignInManager<Ecommerce.Entities.Concrete.User>
    @inject UserManager<Ecommerce.Entities.Concrete.User>*@
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <link href="https://cdn.datatables.net/buttons/1.6.3/css/buttons.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous" />
    <link href="//cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
    <title>E-Ticaret Sistemi</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">E-Ticaret</a>
            <ul class="navbar-nav mr-auto">


                @if (User.Identity.IsAuthenticated)
                {

                    <li class="nav-item">
                        <a asp-controller="Admin" asp-action="Index" class="nav-link">Ürün Bilgileri</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link">Kategori Bilgileri</a>
                    </li>

                    <li class="nav-item">
                        <a asp-controller="Cart" asp-action="Index" class="nav-link">Sepet</a>
                    </li>
                }
            </ul>

            <ul class="navbar-nav mr-auto">

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a asp-controller="User" asp-action="Index" class="nav-link">@User.Identity.Name</a>
                    </li>

                    <li class="nav-item">
                        <a asp-controller="User" asp-action="CıkısYap" class="nav-link">Çıkış Yap</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a asp-controller="User" asp-action="KayıtOl" class="nav-link">Üye Ol</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="User" asp-action="Index" class="nav-link">Giriş Yap</a>
                    </li>
                }


            </ul>
        </div>
    </nav>

    <div class="container pt-100 mb-5">
        @RenderBody()
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.3/js/dataTables.buttons.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.3/js/buttons.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@@10"></script>

    @await RenderSectionAsync("Scripts", false);

</body>
</html>

Ecommerce.UI/Views/Shared/_slider.cshtml
<div id="mySlider" class="carousel slide mb-3" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#mySlider" data-slide-to="0" class="active"></li>
        <li data-target="#mySlider" data-slide-to="1"></li>
        <li data-target="#mySlider" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/slider1.png" class="d-block img-fluid" />
        </div>
        <div class="carousel-item">
            <img src="~/img/slider2.png" class="d-block img-fluid" />
        </div>
        <div class="carousel-item">
            <img src="~/img/slider3.png" class="d-block img-fluid" />
        </div>
    </div>

    <a href="#mySlider" data-slide="prev" class="carousel-control-prev">
        <span class="carousel-control-prev-icon"></span>
    </a>

    <a href="#mySlider" data-slide="next" class="carousel-control-next">
        <span class="carousel-control-next-icon"></span>
    </a>


</div>